export enum AsterismContext {
  westcallIn = 'westcall-in',
  kolchuginoIn = 'kolchugino-in',
  pyatigorskIn = 'pyatigorsk-in',
  chelyabinskIn = 'chelyabinsk-in',
  krasnodarIn = 'krasnodar-mango-in',
  krasnodarDirect = 'krasnodar-mango-direct-in',
  nizhniyIn = 'nizhniy-in',
  nizhniyYandex = 'nizhniy-yandex-in',
  mangoSamara = 'mango-samara-in',
  mangoSpb = 'mango-spb-in',
  mangoVoronezh = 'mango-voronezh-in',
  mangoVoronezhDirect = 'mango-voronezh-direct-in',
  mangoMoscowYandex = 'mango-moscow-yandex-in',
  mamgoNovnosibirsk = 'mango-novnosibirsk-in',
  mangoUfa = 'mango-ufa-in',
}

export enum IdTrunk3CX {
  krasnodarIn = '10028',
  krasnodarDirect = '10004',
  nizhniyIn = '10026',
  nizhniyYandex = '10003',
  mangoSamara = '10030',
  mangoSpb = '10027',
  mangoVoronezh = '10025',
  mangoVoronezhDirect = '10005',
  westcallIn = '10007',
  mangoMoscowYandex = '10029',
  pyatigorskIn = '10006',
  chelyabinskIn = '10024',
  beronet = '10021',
  kolchuginoIn = '10008',
}
